version: "3.8"
services:
  db:
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=caching_sha2_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: kanban
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: kanban
      MYSQL_DATABASE: local-brackets-of-love

  app:
    build:
      context: ./
      dockerfile: local.Dockerfile
    command: ./bin/dev
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: kanban
      DB_NAME: local-brackets-of-love
      RAILS_MAX_THREADS: 5
      BUNDLE_PATH: /bundle
    volumes:
      - ./:/app
      - bundle:/bundle
      - ./node_modules:/node_modules
    ports:
      - 3000:3000
    depends_on:
      - db
    links:
      - db

  test-app:
    build:
      context: ./
      dockerfile: local.Dockerfile
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: kanban
      DB_NAME: local-brackets-of-love
      RAILS_MAX_THREADS: 5
      BUNDLE_PATH: /bundle
    volumes:
      - ./:/app
      - bundle:/bundle
    ports:
      - 3001:3001
    depends_on:
      - db
    links:
      - db

  test-react:
    build:
      context: ./
      dockerfile: local.Dockerfile
    volumes:
      - ./:/app
      - bundle:/bundle
    ports:
      - 3002:3002

volumes:
  db:
    driver: local
  bundle: