apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: develop-mysql-persistent-volume-claim
  namespace: develop
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi


# kubectl apply -f deploy/develop-mysql-pvc.yaml
# kubectl get pvc --namespace=develop
# kubectl describe pvc develop-mysql-persistent-volume-claim