---
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 3306
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  database: <%= ENV['DB_NAME'] %>
  host: <%= ENV['DB_HOST'] %>

development:
  <<: *default

test:
  <<: *default
  database: test-brackets-of-love
  <% if ENV['CI'] %>
  host: 127.0.0.1
  username: root
  password:
  <% end %>

develop:
  <<: *default

production:
  <<: *default