---
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  database: <%= ENV['DB_NAME'] %>
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default


# base: &base
#   adapter: mysql2
#   encoding: utf8mb4
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

# default: &default
#   <<: *base
#   # username: <%= ENV['DB_USERNAME'] %>
#   # password: <%= ENV['DB_PASSWORD'] %>
#   # host: <%= ENV['DB_HOST'] %>
#   # database: <%= ENV['DB_NAME'] %>

# development:
#   <<: *base
#   username: root
#   password: password
#   host: db
#   database: db