# apiVersion: batch/v1
# kind: Job
# metadata:
#   name: develop-app
#   labels:
#     app: develop-app
#     group: db
#   namespace: develop
# spec:
#   template:
#     metadata:
#       labels:
#         app: develop-app
#         group: db
#     spec:
#       containers:
#       - command:
#         - rails
#         - db:create:all
#         - db:schema:load
#         envFrom:
#         - configMapRef:
#             name: develop-mysql-config
#         image: local/brackets-of-love:latest
#         imagePullPolicy: IfNotPresent
#         name: develop-app
#       restartPolicy: Never


apiVersion: batch/v1
kind: Job
metadata:
  name: develop-db-create
  namespace: develop
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: develop-db-create
          image: local/brackets-of-love:latest
          imagePullPolicy: Never
          # readinessProbe:
          #   httpGet:
          #     # httpHeaders:
          #     # - name: Host
          #     #   value: example.com
          #     path: /robots.txt
          #     port: 3000
          #   initialDelaySeconds: 10
          #   periodSeconds: 10
          #   timeoutSeconds: 2
          env:
          - name: DB_HOST
            value: develop-db-service
          - name: DB_USER
            value: user
          - name: DB_PASSWORD
            value: kanban
          - name: DB_NAME
            value: develop-brackets-of-love
          command: ['rails']
          args: ['db:create', 'db:schema:load']

          # rails aborted!
# ActiveRecord::
# : Can't connect to MySQL server on 'develop-db' (115)