apiVersion: batch/v1
kind: Job
metadata:
  name: develop-db-migrate
  labels:
    app: develop-app
    group: db
  namespace: develop
spec:
  template:
    metadata:
      labels:
        app: develop-app
        group: db
    spec:
      containers:
      - command:
        - rails
        - db:migrate
        envFrom:
        - configMapRef:
            name: develop-mysql-config
        image: local/brackets-of-love:latest
        imagePullPolicy: IfNotPresent
        name: develop-app
      restartPolicy: Never