name: CI/CD

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop

env:
  GCP_PROJECT: secrets.GCP_PROJECT
  MYSQL_ROOT_PASSWORD: secrets.DEV_MYSQL_ROOT_PASSWORD
  MYSQL_USERNAME: secrets.DEV_MYSQL_USERNAME
  MYSQL_PASSWORD: secrets.DEV_MYSQL_PASSWORD
  MYSQL_DATABASE: secrets.DEV_MYSQL_DATABASE

jobs:
  deploy_develop:
    name: Deploy Develop to Google Cloud Platform
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2