name: CI/CD

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop

env:
  GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
  MYSQL_ROOT_PASSWORD: ${{ secrets.DEV_MYSQL_ROOT_PASSWORD }}
  MYSQL_USERNAME: ${{ secrets.DEV_MYSQL_USERNAME }}
  MYSQL_PASSWORD: ${{ secrets.DEV_MYSQL_PASSWORD }}
  MYSQL_DATABASE: ${{ secrets.DEV_MYSQL_DATABASE }}

jobs:
  deploy_develop:
    name: Deploy Develop
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - id: 'get-credentials'
        uses: 'google-github-actions/get-gke-credentials@v1'
        with:
          cluster_name: '${{ secrets.GCP_CLUSTER }}'
          location: '${{ secrets.GCP_LOCATION }}'

      - name: Login to GCR
        uses: docker/login-action@v2
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCP_CREDENTIALS }}

# TODO: ADD COMMITS TO TAGS
      - name: Deploy
        run: |
          docker build --build-arg RAILS_MASTER_KEY=${{ secrets.RAILS_MASTER_KEY }} -t develop/brackets-of-love:latest .
          docker tag develop/brackets-of-love:latest us.gcr.io/${{ secrets.GCP_PROJECT }}/develop:latest
          docker push us.gcr.io/${{ secrets.GCP_PROJECT }}/develop:latest
          envsubst < ./deploy/develop/develop-app-deployment.yaml | kubectl apply -f - --namespace=develop
          envsubst < ./deploy/develop/develop-mysql-config.yaml | kubectl apply -f - --namespace=develop
          kubectl rollout restart deployment.apps/develop-app --namespace=develop
          kubectl get all --namespace=develop