name: CI/CD

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop

env:
  GCP_PROJECT: secrets.GCP_PROJECT
  MYSQL_ROOT_PASSWORD: secrets.DEV_MYSQL_ROOT_PASSWORD
  MYSQL_USERNAME: secrets.DEV_MYSQL_USERNAME
  MYSQL_PASSWORD: secrets.DEV_MYSQL_PASSWORD
  MYSQL_DATABASE: secrets.DEV_MYSQL_DATABASE

jobs:
  deploy_develop:
    name: Deploy Develop
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - id: 'get-credentials'
        uses: 'google-github-actions/get-gke-credentials@v1'
        with:
          cluster_name: 'brackets-of-love-cluster'
          location: 'us-central1'

      - name: Deploy
        run: |
          envsubst < ./deploy/develop/develop-app-deployment.yaml | kubectl apply -f - --namespace=develop
          envsubst < ./deploy/develop/develop-mysql-config.yaml | kubectl apply -f - --namespace=develop
          kubectl rollout restart deployment.apps/develop-app --namespace=develop
          kubectl get all --namespace=develop