apiVersion: apps/v1
kind: Deployment
metadata:
  name: develop-mysql
  namespace: develop
  labels:
    app: develop-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: develop-mysql
  template:
    metadata:
      labels:
        app: develop-mysql
    spec:
      containers:
        - image: mysql:8
          name: develop-mysql
          args:
            - "--default-authentication-plugin=caching_sha2_password"
          envFrom:
            - configMapRef:
                name: develop-mysql-config
          ports:
            - containerPort: 3306
              name: develop-mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-volumeclaim