apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: develop-ingress-service
  namespace: develop
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:  
              service:
                name: develop-app
                port:
                  number: 3000