# apiVersion: v1
# kind: Service
# metadata:
#   name: develop-db
# spec:
#   selector:
#     name: develop-db
#   ports:
#     - protocol: TCP
#       port: 3306
#       targetPort: 3306
#   type: NodePort


# apiVersion: v1
# kind: Service
# metadata:
#   name: develop-db
#   labels:
#     app: develop-app
# spec:
#   ports:
#     - port: 3306
#   selector:
#     app: develop-app
#     tier: mysql
#   clusterIP: None

# apiVersion: v1
# kind: Service
# metadata:
#   name: develop-db-service
# spec:
#   selector:
#     name: develop-db-service
#   ports:
#     - protocol: TCP
#       port: 3306
#       targetPort: 3306
#   type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: develop
  labels:
    app: mysql
spec:
  type: ClusterIP
  ports:
    - port: 3306
  selector:
    app: mysql